/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103011-g6f20685228-20210719"
#endif /* AVUTIL_FFVERSION_H */
